services:
  xlitixnftbot:
    image: falkonxl/xlitixnftbot
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "agentbot.js"]
