name: Trigger auto deployment for xlitix-nftbot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/xlitix-nftbot-AutoDeployTrigger-8279be89-bc66-4064-855f-ade317977b41.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
      packages: write

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
         docker build . --tag ghcr.io/falkonxl/xlitix-nftbot:latest
         docker push ghcr.io/falkonxl/xlitix-nftbot:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.XLITIXNFTBOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.XLITIXNFTBOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.XLITIXNFTBOT_AZURE_SUBSCRIPTION_ID }}

      - name: Push container image to registry
        uses: azure/cli@v2
        with:
          inlineScript: |
            az extension add --name containerapp --upgrade
            az containerapp registry set -n xlitix-nftbot-4 -g xlitix --server ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
            replicaset_containers=$(\
              az containerapp show --name xlitix-nftbot-4 \
                  --resource-group xlitix \
                  --query 'properties.template.containers[*].name' \
                  --output tsv \
                  --only-show-errors \
                  )
            for container in $replicaset_containers; do
              az containerapp update \
                --resource-group xlitix  \
                --name xlitix-nftbot-4 \
                --container-name $container \
                --image ghcr.io/falkonxl/xlitix-nftbot:054c5f0a8510ce0ef2762767d599e8c9a1c3d49b \
                --only-show-errors
            done

