name: Trigger auto deployment for xlitix-nftbot-4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/xlitix-nftbot-4-AutoDeployTrigger-4812d7c3-1b82-44cf-8a5c-dc7f705a9877.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.XLITIXNFTBOT4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.XLITIXNFTBOT4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.XLITIXNFTBOT4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.XLITIXNFTBOT4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.XLITIXNFTBOT4_REGISTRY_PASSWORD }}
          containerAppName: xlitix-nftbot-4
          resourceGroup: xlitix
          imageToBuild: ghcr.io/xlitix-nftbot-4:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


